name       : asio
version    : 1.28.0
release    : 2
source     :
    - https://downloads.sourceforge.net/project/asio/asio/1.28.0%20%28Stable%29/asio-1.28.0.tar.gz : e854a53cc6fe599bdf830e3c607f1d22fe74eee892f64c81d3ca997a80ddca97
license    : BSL-1.0
homepage   : http://think-async.com/Asio/
component  : programming.library
summary    : Cross-platform C++ library for network and low-level I/O programming
description: |
    Asio is a cross-platform C++ library for network and low-level I/O programming that provides developers with a consistent asynchronous model using a modern C++ approach
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
patterns   :
    - /*
