name       : asio
version    : 1.26.0
release    : 1
source     :
    - https://sourceforge.net/projects/asio/files/asio/1.26.0%20%28Stable%29/asio-1.26.0.tar.gz : 72576e1fe0bc714b9f99943183b91ac51a3eae9cad791b228f77adee674d1b09
license    : BSL-1.0
homepage   : http://think-async.com/Asio/
component  : programming.library
summary    : Cross-platform C++ library for network and low-level I/O programming
description: |
    Asio is a cross-platform C++ library for network and low-level I/O programming that provides developers with a consistent asynchronous model using a modern C++ approach
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
patterns   :
    - /*
